dashboard/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^create-sfc/', views.create_sfc_form, name='create_sfc'),
    url(r'^create-vnfd/', views.create_vnfd_form, name='create_vnfd'),
    url(r'^create-vnf/', views.create_vnf_form, name='create_vnf'),
    url(r'^create-classifier/', views.create_classifier_form, name='create_classifier'),
    url(r'^create-network/', views.create_network_form, name='create_network'),
    url(r'^create-vm/', views.create_vm_form, name='create_vm'),
    url(r'^vnfs/', views.vnfs_table, name='vnfs_table'),
    url(r'^vnfds/', views.vnfds_table, name='vnfds_table'),
    url(r'^networks/', views.networks_table, name='networks_table'),
    url(r'^delete/', views.deleteJSON, name='deleteJSON'),
    url(r'^mapdata/', views.networksJSON, name='networksJSON'),
]

maestro/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^dashboard/', include('dashboard.urls')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='/dashboard/', permanent=False)),
]

dashboard/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models

class VNF(models.Model):
	name = models.CharField(max_length=200)
	description = models.TextField()

dashboard/forms.py
from django import forms


class SFCForm(forms.Form):
	sfc_name = forms.CharField(label='sfc_name')
	vnfs = forms.CharField(widget=forms.HiddenInput)


class NetworkForm(forms.Form):
	net_name, net_cidr, net_dns, net_dhcp_start, net_dhcp_end = (forms.CharField(),)*5


class VNFForm(forms.Form):
	vnf_name, vnfd_id = (forms.CharField(),)*2

class ClassifierForm(forms.Form):
	classifier_name, src_port, dst_port, netproto = (forms.CharField(),)*4
	sfc_id = forms.CharField(widget=forms.HiddenInput)

dashboard/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.template import loader
from django.contrib.auth.decorators import login_required

from sinfonia_api import *
from forms import *


@login_required
def vnfs_table(request):
    if request.method == 'POST':
        return HttpResponse(request)

    context = dict()
    context['vnfs'] = list_vnfs()['result']

    return HttpResponse(loader.get_template('vnfs_table.html').render(context, request))


@login_required
def vnfds_table(request):
    if request.method == 'POST':
        return HttpResponse(request)

    context = dict()
    context['vnfds'] = list_vnfds()['result']
    context['nodes'] = list_vnfs()['result']


    return HttpResponse(loader.get_template('vnfds_table.html').render(context, request))

@login_required
def networksJSON(request):
    server_dict = {}
    for server in list_servers()['result']:
        server_dict[server['ID']] = server

    host_dict = {}
    for host in list_nodes()['result']:
        host_dict[host['Hypervisor hostname']] = host
        for server in get_host_servers(host['Hypervisor hostname']):
            if server in server_dict: server_dict[server]['host'] = host['Hypervisor hostname']

    net_dict = {}
    for network in list_networks()['result']:
        net_dict[network['name']] = network
        net_dict[network['name']]['subnets'] = net_dict[network['name']]['subnets'].split(' ')[-1]
    if 'admin_floating_net' in net_dict: del net_dict['admin_floating_net']

    vnf_dict = {}
    for vnf in list_vnfs()['result']:
        # Gather data
        vnf_details = show_vnf(vnf['name'])['result']
        server_id = get_server_id(vnf_details['instance_id'])
        networks = (server_dict[server_id]['Networks'].split(', ') if server_id != '' else [])

        # Write dictionary entry
        vnf_dict[vnf['id']] = {}
        vnf_dict[vnf['id']]['name'] = vnf['name']
        vnf_dict[vnf['id']]['network'] = (networks[0].split('=')[0] if len(networks) > 0 else 'None')
        vnf_dict[vnf['id']]['network_ip'] = (networks[0].split('=')[1] if len(networks) > 0 else 'None')
        vnf_dict[vnf['id']]['public_ip'] = (networks[1] if len(networks) > 1 else 'None')
        vnf_dict[vnf['id']]['status'] = (server_dict[server_id]['Status'] if server_id != '' else vnf['status'])
        vnf_dict[vnf['id']]['host'] = (server_dict[server_id]['host'] if server_id != '' else 'None')

    ret = {'networks': net_dict, 'hosts': host_dict, 'vnfs': vnf_dict}
    return JsonResponse(ret)


@login_required
def networks_table(request):
    if request.method == 'POST':
        return HttpResponse(request)

    context = dict()
    context['networks'] = list_networks()['result']

    return HttpResponse(loader.get_template('networks_table.html').render(context, request))


@login_required
def create_sfc_form(request):
    if request.method == 'POST':
        sfc_form = SFCForm(request.POST)
        if sfc_form.is_valid():
            sfc_name = sfc_form.cleaned_data['sfc_name']
            vnf_list = sfc_form.cleaned_data['vnfs'].split('&')
            vnf_list = [vnf.replace('[]=','-') for vnf in vnf_list]
            r = create_sfc(sfc_name, vnf_list)
            message = ((r['result']['message'] + '\n') if 'message' in r['result'] else '') + r['error']
            return HttpResponse(message, content_type="text/plain")
    context = dict()
    context['vnfs'] = list_vnfs()['result']

    return HttpResponse(loader.get_template('create_sfc.html').render(context, request))


@login_required
def create_vnfd_form(request):
    if request.method == 'POST':
        vnfd_name = request.POST['vnfd_name']
        description = request.POST['description']
        image = request.POST['image']
        node = request.POST['node']
        network = request.POST['network']
        flavor = request.POST['flavor']
        vnfd_dict = {"template_name": vnfd_name + "-vnfd",
                     "description": description,
                     "service_properties": {
                       "Id": vnfd_name + "-vnfd",
                       "vendor": "tacker",
                       "version": 1,
                       "type": [
                         vnfd_name + "-vnf"
                       ]
                     },
                     "vdus": {
                       "vdu1": {
                         "id": "vdu1",
                         "vm_image": image,
                         "instance_type": flavor,
                         "service_type": vnfd_name + "-vnf",
                         "network_interfaces": {
                           "management": {
                             "network": network,
                             "management": True
                           }
                         },
                         "placement_policy": {
                           "availability_zone": "nova:"+node
                         },
                         "auto-scaling": "noop",
                         "monitoring_policy": "noop",
                         "failure_policy": "respawn",
                         "config": {
                           "param0": "key0",
                           "param1": "key1"
                         }
                       }
                      }
                     }
        r = create_vnfd(vnfd_dict)
        message = ((r['result']['message'] + '\n') if 'message' in r['result'] else '') + r['error']
        return HttpResponse(message, content_type="text/plain")

    context = dict()
    context['images'] = list_images()['result']
    context['nodes'] = list_nodes()['result']
    context['networks'] = list_networks()['result']
    context['flavors'] = list_flavors()['result']

    return HttpResponse(loader.get_template('create_vnfd.html').render(context, request))


@login_required
def create_vnf_form(request):
    if request.method == 'POST':
        vnf_form = VNFForm(request.POST)
        if vnf_form.is_valid():
            vnf_name = vnf_form.cleaned_data['vnf_name']
            vnfd_id  = vnf_form.cleaned_data['vnfd_id']
            r = create_vnf(vnf_name, vnfd_id)
            message = ((r['result']['message'] + '\n') if 'message' in r['result'] else '') + r['error']
            return HttpResponse(message, content_type="text/plain")
        return HttpResponse(vnf_form)

    context = dict()
    context['vnfds'] = list_vnfds()['result']

    return HttpResponse(loader.get_template('create_vnf.html').render(context, request))


@login_required
def create_vm_form(request):
    if request.method == 'POST':
        return HttpResponse(request)

    context = dict()
    context['images'] = list_images()['result']
    context['nodes'] = list_nodes()['result']
    context['networks'] = list_networks()['result']
    context['flavors'] = list_flavors()['result']

    return HttpResponse(loader.get_template('create_vm.html').render(context, request))


@login_required
def create_classifier_form(request):
    if request.method == 'POST':
        classifier_form = ClassifierForm(request.POST)
        #return HttpResponse(classifier_form)
        if classifier_form.is_valid():
            classifier_name = classifier_form.cleaned_data['classifier_name']
            src_port = classifier_form.cleaned_data['src_port']
            dst_port = classifier_form.cleaned_data['dst_port']
            netproto = classifier_form.cleaned_data['netproto']
            sfc_id    = classifier_form.cleaned_data['sfc_id']
            r = create_classifier(classifier_name, sfc_id, src_port, dst_port, netproto)
            message = ((r['result']['message'] + '\n') if 'message' in r['result'] else '') + r['error']
            return HttpResponse(message, content_type="text/plain")
        return HttpResponse(classifier_form)

    context = dict() 
    return HttpResponse(loader.get_template('create_classifier.html').render(context, request))


@login_required
def create_network_form(request):
    if request.method == 'POST':
        net_form = NetworkForm(request.POST)
        if net_form.is_valid():
            net_name = net_form.cleaned_data['net_name']
            net_cidr = net_form.cleaned_data['net_cidr']
            net_dns = net_form.cleaned_data['net_dns']
            net_dhcp_start = net_form.cleaned_data['net_dhcp_start']
            net_dhcp_end = net_form.cleaned_data['net_dhcp_end']
            r = create_network(net_name, net_cidr, net_dns, net_dhcp_start, net_dhcp_end)
            message = ''
            for k, i in r.iteritems():
                message += k + ':\n' + \
                           '-' * (len(k)+1) + '\n' + \
                           ((i['result']['message'] + '\n') if 'message' in i['result'] else '') + \
                           i['error'] + '\n\n'
            return HttpResponse(message, content_type="text/plain")
    context = dict()
    return HttpResponse(loader.get_template('create_network.html').render(context, request))


@login_required
def index(request):
    vnf_dict = {} #key = vnf id
    for vnf in list_vnfs()['result']:
        vnf_dict[vnf['id']] = vnf
        #Uncomment next line for extended vnf attributes (slow)
        #vnf_dict[vnf['id']].update(show_vnf(vnf['name'])['result'])

    classifier_dict = {} #key=sfc id
    for classifier in list_classifiers()['result']:
        classifier.update(show_classifier(classifier['id'])['result'])
        classifier_dict[classifier['chain']] = classifier

    sfc_list = list_sfcs()['result']
    for i in range(len(sfc_list)):
        vnfs = ''
        sfc_list[i].update(show_sfc(sfc_list[i]['name'])['result'])
        for j in range(len(sfc_list[i]['chain'])):
            sfc_list[i]['chain'][j] = vnf_dict[sfc_list[i]['chain'][j]]
            vnfs += ', ' + sfc_list[i]['chain'][j]['name']
        if len(vnfs) > 2: sfc_list[i][u'vnfs'] = vnfs[2:]
        if sfc_list[i]['id'] in classifier_dict:

dashboard/templates/create_classifier.html
{% extends 'base_html.html' %}
{% load custom_filters %}

{% block content %}
  <div class="page-header">
              <h3>Create new classifier</h3>            
          </div>
  <form id="create_form" action="javascript:create_item('/dashboard/create-classifier/','/dashboard/','#create_form');">
    {% csrf_token %}
    <div class="form-group">
      <label for="id_classifier_name">Classifier Name</label>
      <input type="text" class="form-control" id="id_classifier_name" name="classifier_name" placeholder="Enter name">
    </div>

    <div class="form-group">
      <label for="id_src_port">Source Port</label>
      <input type="text" class="form-control" id="id_src_port" name="src_port" placeholder="Source Port">
    </div>    

    <div class="form-group">
      <label for="id_dst_port">Destination Port</label>
      <input type="text" class="form-control" id="id_dst_port" name="dst_port" placeholder="Destination Port">
    </div>

    <div class="form-group">
      <label for="id_select_netproto">Protocol</label>
      <select class="form-control" id="id_select_netproto" name="netproto">
        <option value="6">UDP</option>
        <option value="17">TCP</option>
      </select>
    </div>

    <div class="form-group">
      <button type="submit" class="btn btn-primary form-control">Create classifier</button>
    </div>
    <input type="hidden" id="id_sfc_id" name="sfc_id" value="">
  </form>

<script type="text/javascript">

  var getUrlParameter = function getUrlParameter(sParam) {
      var sPageURL = decodeURIComponent(window.location.search.substring(1)),
          sURLVariables = sPageURL.split('&'),
          sParameterName,
          i;

      for (i = 0; i < sURLVariables.length; i++) {
          sParameterName = sURLVariables[i].split('=');

          if (sParameterName[0] === sParam) {
              return sParameterName[1] === undefined ? true : sParameterName[1];
          }
      }
  };

  $(document).ready(function(){
    console.log(getUrlParameter('sfc_id'));
    $('#id_sfc_id').val(getUrlParameter('sfc_id'));
  });
</script>
{% endblock content %}

dashboard/templates/create_network.html
{% extends 'base_html.html' %}
{% load custom_filters %}

{% block content %}
  <div class="page-header">
              <h3>Create new network</h3>            
          </div>
  <form id="create_form" action="javascript:create_item('/dashboard/create-network/','/dashboard/networks/','#create_form');">
    {% csrf_token %}
    <div class="form-group">
      <label for="id_net_name">Network Name</label>
      <input type="text" class="form-control" id="id_net_name" name="net_name" placeholder="Enter name">
    </div>
    <div class="form-group">
      <label for="id_net_cidr">Network CIDR</label>
      <input type="text" class="form-control" id="id_net_cidr" name="net_cidr" placeholder="Network CIDR">
    </div>
    <div class="form-group">
      <label for="id_net_dns">DNS Server IP</label>
      <input type="text" class="form-control" id="id_net_dns" name="net_dns" placeholder="DNS IP">
    </div>
    <div class="form-group">
      <label for="id_net_dhcp_start">DHCP IP Pool Start</label>
      <input type="text" class="form-control" id="id_net_dhcp_start" name="net_dhcp_start" placeholder="DHCP Start">
    </div>
    <div class="form-group">
      <label for="id_net_dhcp_end">DHCP IP Pool End</label>
      <input type="text" class="form-control" id="id_net_dhcp_end" name="net_dhcp_end" placeholder="DHCP End">
    </div>
    <div class="form-group">
      <button type="submit" class="btn btn-primary form-control">Create network</button>
    </div>
  </form>

{% endblock content %}

dashboard/templates/create_sfc.html
{% extends 'base_html.html' %}
{% block content %}
        <div class="page-header">
            <h3>Create new Service Function Chain</h3>            
        </div>
        <form id="form-create-sfc" action="javascript:create_sfc();">
            {% csrf_token %}
            <div class="col-md-12 form-group row">
                <label for="sfc-name">Name</label>
                <input type='text' style="margin-left: 20px" class="" name='sfc-name' id='id_sfc_name' placeholder="SFC Name">
            </div>  
            <div id="sortable-container" style="margin-top: 30px" class="form-group">
                <h4>Chain design</h4>
                <div id="sortable" class="connectedSortable col-md-12">
                    <div id="start" class="panel panel-warning arrow_box" style="margin: 15px 15px 15px 15px">
                        <div class="panel-heading">
                            <h4 class="panel-title">Start</h4>
                        </div>
                        <div class="panel-body">
                                VNF Description
                        </div>
                    </div>
                    <div id="vnf_placeholder" class="panel panel-warning arrow_box" style="margin: 15px 15px 15px 15px">
                        <div class="panel-heading">
                            <h4 class="panel-title">VNF</h4>
                            <!-- Watch Out: Here We must use the effect name in the data tag-->
                            <span id="remove-button" class="pull-right clickable" data-effect="remove"><i class="glyphicon glyphicon-remove"></i></span>
                        </div>
                        <div class="panel-body">
                            VNF Description
                        </div>
                    </div>
                    <div id="end" class="panel panel-warning" style="text-align:center; margin: 15px 15px 15px 15px">
                        <div class="panel-heading">
                            <h4 class="panel-title">End</h4>
                        </div>
                        <div class="panel-body">
                                VNF Description
                        </div>
                    </div>
                </div>
                <h4>Available VNFs</h4>
                <div id="sortable2" class="connectedSortable col-md-12 form-group">
                    {% for vnf in vnfs %}
                        <div id="{{vnf.name}}" class="panel panel-warning" style="text-align:center; margin: 15px 15px 15px 15px">
                            <div class="panel-heading">
                                <h4 class="panel-title">{{ vnf.name }}</h4>
                                <span id="remove-button" class="pull-right clickable" data-effect="remove" style="display: none"><i class="glyphicon glyphicon-remove"></i></span>

                            </div>
                            <div class="panel-body">
                                {{ vnf.description }}
                            </div>
                        </div>   
                    {% endfor %}
                </div>
            </div>
            <div class="form-group">
                <input class="btn btn-primary form-control" type='submit' value="Create SFC"></input>
            </div>
        </form>


    <script type="text/javascript">

        //var count = 0;

        $("#sortable2").sortable({
            containment: "#sortable-container",
            connectWith: ".connectedSortable",
            helper: function (e, li) {
                this.copyHelper = li.clone().insertAfter(li);
                $(this).data('copied', false);
                return li.clone();
            },
            stop: function () {
                var copied = $(this).data('copied');
                if (!copied) {
                    this.copyHelper.remove();
                }
                this.copyHelper = null;
            }
        }).disableSelection();

        $("#sortable").sortable({ 
            items: "div:not(:last-child,:first-child)",
            cancel: '#end,#start',
            containment: "#form-create-sfc", 
            receive: function (e, ui) {
                //var new_id = ui.item.attr('id') + '_' + count;
                //console.log(new_id);
                ui.sender.data('copied', true);
                ui.item.addClass('arrow_box');
                ui.item.css('text-align', 'left');
                //ui.item.attr('id', new_id);
                ui.item.find("#remove-button").css('display', 'block');
                $('#vnf_placeholder').remove();
                //count++;
            } 
        }).disableSelection();

        function create_sfc(){
            $("body").addClass("loading");
            $.post('/dashboard/create-sfc/',
                {'sfc_name': $('#id_sfc_name').val(), 'vnfs': $('#sortable').sortable('serialize')},
                function (data, textStatus) {
                    $("body").removeClass("loading");
                    $('<div title="Creation request result"><textarea readonly rows="8" cols="90" >' + data + '</textarea></div>').dialog({
                        resizable: false,
                        width: 'auto',
                        dialogClass: "no-close",
                        modal: true,
                        zindex: 2000,
                        closeOnEscape: false,
                        buttons: {
                            'Ok': function () {
                                $(location).attr('href', '/dashboard/');
                                $("body").addClass("loading");
                            }
                        }
                    });
                },
                'text');
        }
    </script>

    <script>
        $(function(){
            $('.clickable').on('click',function(){
                var effect = $(this).data('effect');
                    $(this).closest('.panel')[effect]();
                })
        })
    </script>

{% endblock content %}

dashboard/templates/create_vm.html
{% extends 'base_html.html' %}
{% load custom_filters %}

{% block content %}
  <div class="page-header">
              <h3>Create new Virtual Machine</h3>            
          </div>
  <form>
    <div class="form-group">
      <label for="vm-name">Virtual Machine Name</label>
      <input type="text" class="form-control" id="vm-name" placeholder="Enter name">
    </div>
    <div class="form-group">
      <label for="select-image">Image</label>
      <select class="form-control" id="select-image">
        {% for i in images %}
        <option>{{ i.Name }}</option>
        {% endfor %}
      </select>
    </div>

    <div class="form-group">
      <label for="select-node">Node</label>
      <select class="form-control" id="select-node">
        {% for i in nodes %}
        <option>{{ i | get_item:"Hypervisor hostname" }}</option>
        {% endfor %}
      </select>
    </div>

    <div class="form-group">
      <label for="select-network">Network</label>
      <select class="form-control" id="select-network">
        {% for i in networks %}
        <option>{{ i.name }}</option>
        {% endfor %}
      </select>
    </div>

    <div class="form-group">
      <label for="select-flavor">Flavor</label>
      <select class="form-control" id="select-flavor">
        {% for i in flavors %}
        <option>{{ i.Name }}</option>
        {% endfor %}
      </select>
    </div>
    <div class="form-group">
      <button type="submit" class="btn btn-primary form-control">Create VM</button>
    </div>
  </form>
{% endblock content %}

dashboard/templates/create_vnf.html
{% extends 'base_html.html' %}
{% load custom_filters %}

{% block content %}
  <div class="page-header">
              <h3>Create new VNF</h3>
          </div>
  <form id="create_form" action="javascript:create_item('/dashboard/create-vnf/','/dashboard/vnfs/','#create_form');">
    {% csrf_token %}
    <div class="form-group">
      <label for="id_vnf_name">VNF Name</label>
      <input type="text" class="form-control" id="id_vnf_name" name="vnf_name" placeholder="Enter name">
    </div>

    <div class="form-group">
      <label for="id_vnfd_id">VNF Descriptor</label>
      <select class="form-control" id="id_vnfd_id" name="vnfd_id">
        {% for vnfd in vnfds %}
        <option value="{{ vnfd.id }}">{{ vnfd.name }}</option>
        {% endfor %}
      </select>
    </div>

    <div class="form-group">
      <button type="submit" class="btn btn-primary form-control">Create VNF</button>  
    </div>
  </form>


{% endblock content %}

dashboard/templates/create_vnfd.html
{% extends 'base_html.html' %}
{% load custom_filters %}

{% block content %}
  <div class="page-header">
      <h3>Create new VNF Descriptor</h3>
  </div>

  <form id="create_form" action="javascript:create_item('/dashboard/create-vnfd/','/dashboard/vnfds/','#create_form');">
    {% csrf_token %}
    <div class="form-group">
      <label for="id_vnfd_name">VNFD Name</label>
      <input type="text" class="form-control" id="id_vnfd_name" name="vnfd_name" placeholder="Enter name">
    </div>

    <div class="form-group">
      <label for="id_vnfd_description">Description</label>
      <input type="text" class="form-control" id="id_vnfd_description" name="description" placeholder="Enter a brief description">
    </div>

    <div class="form-group">
      <label for="id_image">Image</label>
      <select class="form-control" id="id_image" name="image">
        {% for i in images %}
        <option>{{ i.Name }}</option>
        {% endfor %}
      </select>
    </div>

    <div class="form-group">
      <label for="id_node">Node</label>
      <select class="form-control" id="id_node" name="node">
        {% for i in nodes %}
        <option>{{ i | get_item:"Hypervisor hostname" }}</option>
        {% endfor %}
      </select>
    </div>

    <div class="form-group">
      <label for="id_network">Network</label>
      <select class="form-control" id="id_network" name="network">
        {% for i in networks %}
        <option>{{ i.name }}</option>
        {% endfor %}
      </select>
    </div>

    <div class="form-group">
      <label for="id_flavor">Flavor</label>
      <select class="form-control" id="id_flavor" name="flavor">
        {% for i in flavors %}
        <option>{{ i.Name }}</option>
        {% endfor %}
      </select>
    </div>
    <div class="form-group">
      <button type="submit" class="btn btn-primary form-control">Create VNFD</button>  
    </div>
  </form>
{% endblock content %}

dashboard/templates/networks_table.html
{% extends 'base_html.html' %}
{% block content %}
        <div class="page-header">
            <h3>Networks</h3>            
        </div>

        <style type="text/css">
            #topology {
              width: 900px;
              height: 600px;
              border: 1px solid lightgray;
              margin: auto;}
        </style>
        <script type="text/javascript" src="/static/js/vis.min.js"></script>
        <link href="/static/css/vis.min.css" rel="stylesheet" type="text/css" />

        <script type="text/javascript">
                var nodes = [];
                var edges = [];
                var network = null;

            function draw() {
                $.getJSON('/dashboard/mapdata/', function (data) {

                    var DIR = '/static/img/';
                    var EDGE_LENGTH_MAIN = 150;
                    var EDGE_LENGTH_SUB = 30;

                    nodes.push({id: 'nova', label: 'nova', image: DIR + 'switch.png', shape: 'image', size: 20});

                    $.each(data.hosts, function (key, val) {
                        nodes.push({id: key,
                                    label: key,
                                    image: DIR + 'server.png',
                                    shape: 'image',
                                    size: 40
                        });
                        edges.push({from: key, to: 'nova', length: EDGE_LENGTH_SUB, color: 'black'});
                    });

                    $.each(data.networks, function (key, val) {
                        nodes.push({id: key,
                                    label: key,
                                    image: DIR + 'router.png',
                                    shape: 'image',
                                    size: 16,
                                    title: '<b>Subnet</b>: ' + val.subnets
                        });
                    });

                    $.each(data.vnfs, function (key, val) {
                        nodes.push({id: key,
                                    label: val.name,
                                    image: DIR + 'vnf.png',
                                    shape: 'image',
                                    size: 20,
                                    title: '<b>Status:</b> ' + val.status + '<br/><b>Private IP:</b> ' +  val.network_ip + '<br/><b>Public IP:</b> ' + val.public_ip + '<br/><b>ID:</b> ' + key
                        });
                        if (val.host != "None") {edges.push({from: key, to: val.host, length: EDGE_LENGTH_MAIN, dashes: true, color: 'gray'});}
                        if (val.network != "None") {edges.push({from: key, to: val.network, length: EDGE_LENGTH_SUB});}
                    });

                    // create a network
                    var container = document.getElementById('topology');
                    var drawing_data = {nodes: nodes, edges: edges};
                    var options = {physics: {solver: 'repulsion'}};
                    network = new vis.Network(container, drawing_data, options);
                });
            }
        </script>

        <div id="topology">
            <div id=loading class="sk-cube-grid">
                <img style="height: 122.17px; width: 100px; margin-bottom: 17.83pt" src="/static/img/sinfonia.png">
                <div class="sk-cube sk-cube1"></div>
                <div class="sk-cube sk-cube2"></div>
                <div class="sk-cube sk-cube3"></div>
                <div class="sk-cube sk-cube4"></div>
                <div class="sk-cube sk-cube5"></div>
                <div class="sk-cube sk-cube6"></div>
                <div class="sk-cube sk-cube7"></div>
                <div class="sk-cube sk-cube8"></div>
                <div class="sk-cube sk-cube9"></div>
            </div>
            <script type="text/javascript">
                draw();
            </script>
        </div>

        <br /><br />

        <table class="table">
            <thead>
                <tr>
                    <th> ID </th>
                    <th> Name </th>
                    <th> Subnets </th>

                </tr>
            </thead>
            <tbody>
            {% for network in networks %}
                <tr>
                    <td> {{ network.id }} </td>
                    <td> {{ network.name }} </td>
                    <td> {{ network.subnets }} </td>
                    <td><button class="btn btn-danger" onclick="delete_item('{{ network.name }}', 'network');">Delete</button></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

{% endblock content %}

dashboard/templates/vnfs_table.html
{% extends 'base_html.html' %}
{% block content %}
        <div class="page-header">
            <h3>VNFs</h3>            
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th> ID </th>
                    <th> Name </th>
                    <th> Description </th>
                    <th> IP </th>
                    <th> Status </th>

                </tr>
            </thead>
            <tbody>
            {% for vnf in vnfs %}
                <tr>
                    <td> {{ vnf.id }} </td>
                    <td> {{ vnf.name }} </td>
                    <td> {{ vnf.description }} </td>
                    <td> {{ vnf.mgmt_url.vdu1 }} </td>
                    <td> {{ vnf.status }} </td>
                    <td><button class="btn btn-danger" onclick="delete_item('{{ vnf.id }}', 'vnf');">Delete</button></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

{% endblock content %}